title: Gurveer Arora
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gurveer Arora # add your name
author-img: gurveer-arora.jpg # add your photo
about-author: MPhys Graduate. <br> Developer at Scott Logic. <br> Always Learning. <hr> Experience includes with JS, TS, React, C#, Rust and Python. <hr> Some of my projects hosted below, more exist on github. See my blog posts, the topics are anything I find interesting.  # add description
social-github: quarknerd # add your Github handle
social-linkedin: gurveer-arora-87767711a # add your Linkedin handle
social-email: Garora1410@yahoo.co.uk # add your Email address

# projects
projects: 
  - name: Flappy Bird in D3
    link: https://quarknerd.github.io/d3_flappy_bird/
  - name: Game of life in React
    link: https://quarknerd.github.io/react_game-of-life/
  - name: Dice roller in THREEjs
    link: https://quarknerd.github.io/threejs_die_roller/

# # Disqus
# discus-identifier: # add your discus identifier

# # Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-coffeescript

sass:
  sass_dir: assets/css/scss
  style: compressed

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
